//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos
    {
        public int DatosId { get; set; }
        public string Nombre { get; set; }
        public string NumeroTarjeta { get; set; }
        public string NumeroCuenta { get; set; }
        public string Contrasena { get; set; }
        public string DobleContrasena { get; set; }
    }
}
